### PR TITLE
Fix #88 Clean up entity state on createNew exception

### LINKED ISSUE #88: Entity throwing in createNew are still tracked as existing
The recent changes introduced by #87 are not complete.
If an entity throws during `createNew` it is not removed from the tracked active or passive entities.
This prevents any further successful creation of the same entity.

### PR DESCRIPTION
**Pull request by ljacomet**

### CODE REVIEW

File: passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java [hunk 1]
```diff
@@ -709,6 +709,12 @@ public synchronized void create(String entityClassName, String entityName, long
       // Tell the entity to create itself as something new.
       newEntity.createNew();
```
Comment (ljacomet) [inline passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java]: This call happens after the entity has been added to the entity map, so cleanup required in the exception path.
